# 무중단 배포를 위한 yml 설정
spring:
  profiles:
    active: local # 처음 활성화는 local 로 한다는 뜻
    group:
      local: local, common, local_secret
      blue: blue, common, blue_secret
      green: green, common, green_secret

  config:
    import: application-secret.yml

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: blue
  # JPA
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: green
  # JPA
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

serverName: green_server

---

# 실서버 공통
spring:
  config:
    activate:
      on-profile: common
---